// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzhGs1NsRRpsQItv_fompWrX3sE1Bg1fo',
    appId: '1:552867598035:web:003e29c3bf96bce2028e26',
    messagingSenderId: '552867598035',
    projectId: 'suraj-5f2b6',
    authDomain: 'suraj-5f2b6.firebaseapp.com',
    storageBucket: 'suraj-5f2b6.appspot.com',
    measurementId: 'G-EN0B1KSW7E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDN84RGmXsg_3iCW22wyWyqoqWsoW1sTSM',
    appId: '1:552867598035:android:7f86434ea12e51fa028e26',
    messagingSenderId: '552867598035',
    projectId: 'suraj-5f2b6',
    storageBucket: 'suraj-5f2b6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_vCqINwgP2lPwF5vdmwKGdu0ZvtjMito',
    appId: '1:552867598035:ios:d6a74d6a5b5917fc028e26',
    messagingSenderId: '552867598035',
    projectId: 'suraj-5f2b6',
    storageBucket: 'suraj-5f2b6.appspot.com',
    iosBundleId: 'com.example.firebase1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_vCqINwgP2lPwF5vdmwKGdu0ZvtjMito',
    appId: '1:552867598035:ios:d6a74d6a5b5917fc028e26',
    messagingSenderId: '552867598035',
    projectId: 'suraj-5f2b6',
    storageBucket: 'suraj-5f2b6.appspot.com',
    iosBundleId: 'com.example.firebase1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzhGs1NsRRpsQItv_fompWrX3sE1Bg1fo',
    appId: '1:552867598035:web:46d3709f836a0b08028e26',
    messagingSenderId: '552867598035',
    projectId: 'suraj-5f2b6',
    authDomain: 'suraj-5f2b6.firebaseapp.com',
    storageBucket: 'suraj-5f2b6.appspot.com',
    measurementId: 'G-FJW6S0V87P',
  );
}
